== El Diario de John Conran

En varias ocasiones durante los últimos años,
he tenido en mente dejar algunos recuerdos de los tiernos y misericordiosos tratos del
bondadoso Creador para conmigo (indigno como me siento del más pequeño de ellos);
y confío y espero que mi esfuerzo por hacerlo en este momento,
proceda más del deseo de alabar a quien es debido, que de exaltar a la criatura,
a quien sólo le pertenece "`la vergüenza y confusión de rostro.`"

Tengo ahora (1808) sesenta y nueve años,
y aunque los asuntos de mi vida pasada puedan ser consideradas
por muchos de poca importancia para el público,
para quienes no son registradas,
aun así pueden resultar ventajosas para algunos de los que son
conducidos a viajar por la '`senda que el ojo de buitre no ha visto.`'^
footnote:[Job 28:7]
El ojo agudo y perceptivo de la sabiduría humana no ha sido capaz,
en ninguna época del mundo,
de desvelar el misterio que ha estado escondido del sabio y del entendido,
en todas las edades y generaciones.
Pero los patriarcas, profetas y apóstoles, viajeros de vidas sencillas,
y que no estaban familiarizados con esa erudición de la que los paganos se enorgullecían,
caminaron en la experiencia viva de los caminos y
obras de la gracia divina en sus propios corazones,
siguiéndola y obedeciéndola, y de ese modo fueron hechos partícipes de ese pacto de vida,
que sólo viene a través de la aparición espiritual de Jesucristo, dentro de ellos.
Estos (independientemente del nombre externo en cuanto a religión),
mientras obedecían esta luz celestial y la seguían, se convertían en hijos de ella,
y las obras que hacían en obediencia a dicha luz,
eran obras de justicia y aceptadas de sus manos.

Fue de este modo, que muchos que no conocían la ley no sólo fueron ley para sí mismos,^
footnote:[Romanos 2:14]
sino que sus vidas y conductas los hicieron ser luces en el mundo;
quedando reservada la completa manifestación del glorioso día del evangelio,
para la venida y aparición de nuestro Señor y Salvador Jesucristo,
cuyo día vio Abraham en la visión de la vida y se alegró. En la misma vida y luz,
los profetas y hombres santos de antaño predijeron estas buenas nuevas,
según fueron inspirados por el Espíritu Santo.
El hombre, mediante su propia sabiduría y ayudado por todo el aprendizaje adquirido,
por sí mismo o de otros, no ha sido capaz de comprender esta revelación. En efecto,
ese tipo de aprendizaje no fue suficiente para los hombres de épocas anteriores,
ni es suficiente en esta época o generación,
para dar a conocer a Cristo salvadoramente en el interior, la esperanza de gloria,
ni para permitirles a los hombres confesar (en sus vidas y conductas,
gobernados por el santo temor) que Él es el Cristo, el Hijo del Dios vivo.
En realidad, la '`carne y sangre`' no puede revelar esto ahora,
más de lo que pudo revelárselo a Pedro; sino sólo nuestro Padre que está en los cielos.

Creyendo en esta Escritura, que "`nadie conoce al Hijo, sino el Padre,
ni al Padre conoce alguno, sino el Hijo,
y aquel a quien el Hijo lo quiera revelar,`" Mateo 11:27,
hago estas pocas observaciones en la primera parte de esta narración,
porque mi manera de vivir, nacimiento y herencia,
no eran acordes con la fe que profeso hoy.
Y como mi cambio de las señales externas y visibles
(que representan la gracia de Dios para el hombre),
a la gracia interna y espiritual (tipificada por estas sombras),
no fue resultado de mi propia sabiduría o voluntad, ni la de otros,
sino que brotó de las secretas manifestaciones de Su gracia divina en mi corazón,
siento el deseo de dar mi testimonio acerca de esta revelación interna de luz y verdad,
que plenamente creo que viene de Jesucristo,
para redimir a los que la sienten y son obedientes
a ella de toda impiedad y deseos mundanos,
enseñándoles a vivir sobria, justa y piadosamente en este mundo presente.
Tito 2:11-12. En efecto, esta gracia no sólo nos enseña,
sino que también es suficiente para ayudarnos y librarnos en todos los momentos de prueba,
lo que una creencia en ordenanzas externas, o la observación de los tiempos y ceremonias,
nunca pudieron lograr para mí, como se verá en el siguiente relato.

Nací en la ciudad de Dublín, Irlanda, en el año 1739.
Al ser mis padres miembros de la iglesia de Inglaterra, fui criado en dicha profesión,
y tuve la ventaja de recibir una educación bastante liberal bajo la tutela de un clérigo
de esa religión. Después de haber adquirido cierta familiaridad con los clásicos,
antes de tener doce años, fui colocado bajo el cuidado de Abraham Shackleton^
footnote:[Abraham Shackleton fue un anciano muy conocido
y respetado en la Sociedad de Amigos.
Abrió un internado en Ballitore, Irlanda, en 1726, y continuó como director hasta 1756,
cuando la administración de la escuela pasó a su hábil y piadoso hijo Richard Shackleton.]
de Ballitore, donde mis estudios anteriores fueron perfeccionados,
y adquirí cierta familiaridad con el tipo de conocimiento
que me capacitaba para los negocios.
No debo omitir una circunstancia que me sucedió ahí cuando tenía unos trece años,
al ser un ejemplo de la misericordiosa visitación
de la gracia divina hacia mí en mi temprana juventud,
apareciendo como un espíritu de juicio y condenando aquellas
cosas con las que Su bendito Espíritu tiene controversia.
En compañía de algunos de mis compañeros de escuela,
bebí un licor dulce (llamado Shrub) que me dominó. Después de estar en la cama un rato,
sentí que se apoderaban de mí fuertes convicciones que me hacían sentir afligido.
Estas crecieron gradualmente en mí y fueron seguidas
por grandes terrores de muerte y juicio futuro,
lo que me hizo clamar por misericordia y prometer
que nunca sería culpable de lo mismo otra vez.
Mi viejo maestro se acercó a mi cama y se quedó a mi lado, hasta que la prueba amainó,
unos quince minutos después. Estas impresiones, aunque profundas en ese momento,
fueron pronto borradas y pensé muy poco en ellas,
pues estaba más ocupado en las diversiones.

Fui colocado como aprendiz en Lisburn, en el condado de Antrim,
para que aprendiera el oficio del lino.
En esa situación tenía más libertad de la que había experimentado hasta entonces.
Mis conocidos más cercanos eran jóvenes de mi edad,
y habiendo recibido una buena cantidad de dinero por parte de mis parientes,
fui llevado a las diversiones a las que se inclinan los jóvenes.
Tenía un caballo y era muy aficionado a la caza.
Asistía a bailes y a reuniones, a los que era muy adicto,
y eso me llevó al deseo de ropa fina, la cual me permití en grado sumo.
También era aficionado a la música, y tenía una fuerte propensión a cantar y a silbar;
a lo que conduce el amor a la música.
Puedo decir con Salomón,
que di mi corazón para conocer el placer en la mayoría de las formas en
que se les da a los hijos de los hombres--no como dijo el hombre sabio,
'`para conocer qué era el bien de los hijos de los hombres;`'^
footnote:[Eclesiastés 2:3]
no, ese conocimiento fue reservado por el buen Pastor para un día futuro,
cuando se me hizo ver en esa luz que es superior a la palabra escrita,
que esas cosas conducen a las cámaras de muerte.
Pues los amantes de los placeres no son, ni pueden ser, amantes de Dios,^
footnote:[1 Timoteo 5:6]
ya que no hay comunión entre Cristo y Belial.

Continué en esas prácticas y hábitos hasta casi los veinticuatro años,
cuando comencé a sentir que mi mente a menudo era llevada a serias reflexiones,
las cuales poco a poco desgastaron esa disposición
que por tanto tiempo me había llevado a malas compañías,
y a dejar de oír la voz divina,
ese silbo apacible y delicado en mi corazón. Y para la sorpresa de muchos,
algunos de los cuales eran estimables miembros de la comunidad,
dejé de participar en lo que generalmente se denominaban diversiones inocentes.

Me alojaba en el pueblo y a menudo me quedaba en casa.
Mis antiguos compañeros solían llegar y tentarme para que me fuera con ellos,
pero yo me negaba con un semblante que denotaba tal firmeza que los sorprendía,
y oí que se decía que yo estaba perdiendo la razón,
lo que provocaba que otros llegaran a mirarme para ver si era así. No puedo decir cómo,
pero mi disposición a cantar y a silbar (que era mi diversión favorita) desapareció,
y creo que nunca la reanudé;
y aunque mi educación nunca me instruyó a buscar en el interior
aquello que sólo se puede encontrar en el interior,
a menudo era conducido a un secreto recogimiento y retiro en espíritu,
que me llevó a creer (y tal vez a una experiencia palpable),
que "`lo que se conoce acerca de Dios es evidente dentro de ellos.`"^
footnote:[Romanos 1:19 LBLA, RVG]
Mis respiraciones secretas empezaron a ser en pos de Dios,
y estas me llevaron a asistir con frecuencia al culto público.
Raramente dejaba de recibir el pan y el vino, excepto cuando me percibía descalificado.
La recomendación de no acercarse a la mesa del Señor,
de no recibir los elementos indignamente, para no comer y beber mi propia condenación,
había sido un obstáculo con el que había tropezado por mucho tiempo.
Pero un día, en ese momento del culto,
me sentí impedido a irme como de costumbre con los que no participaban de la comunión,
y con mucho temor me acerqué a la mesa y recibí el pan y el vino,
lo cual me dio una gran satisfacción, pues había recibido ese rito de mi iglesia,
y continué dicha práctica por algunos años. Creo que en ese estado mental de búsqueda,
se me permitió probar esa ceremonia y ver para qué servía,
pues yo era un defensor de la religión de mi educación;
más adelante un dignatario de dicha religión me dijo,
que él siempre se alegraba de verme en la iglesia,
ya que mi comportamiento allí era devoto, y que lamentaba perderme.

Yo conocía íntimamente a varios del pueblo llamado Cuáqueros,
y les tenía aprecio y amistad,
pero sus pretensiones de tener una religión más espiritual,
sus declaraciones de inspiración,
y sus reuniones silenciosas con el beneficio que se dice que brota de ellas,
no lo podía disfrutar, ni creer del todo.
Yo era de la opinión de que el Nuevo Testamento contenía
todo lo que era necesario para la salvación del hombre,
pero a veces me sentía desconcertado,
porque no sabía cómo debía poner en práctica sus preceptos--en él encontraba la forma,
pero ¿dónde estaba el poder para cumplirla?
A menudo gemía por la liberación del poder del pecado y de la muerte,
y al igual que muchos de mis compañeros comulgantes de entonces,
creía que no había redención de dicho poder de este lado de la tumba.
Eso me hacía sentir un grado de tranquilidad en las ejecuciones externas, las cuales,
al igual que la ley de antes, '`no hizo perfectos a los que se acercaban;`'^
footnote:[Hebreos 10:1]
sin embargo, creo que a mí me fueron útiles para llevarme al mejor pacto.

Mientras buscaba la redención del pecado y la transgresión,
dejé el pueblo y tomé una granja,
donde he vivido cerca de cuarenta y tres años. Creo que
esta mudanza fue ordenada por la sabiduría del Señor,
ya que me alejó en gran medida de mis antiguos conocidos y hábitos.
Mi tiempo libre lo dedicaba a ocupaciones útiles y agradables para mí;
cultivaba y continuaba con mi negocio de lino.
Asistía al culto público con bastante más constancia que antes,
aunque viviera a unas tres millas del lugar de reunión,
y pensaba que nadie podría sacudir mis ortodoxas opiniones al respecto.
No pensaba hacer una revolución tan importante,
como para cambiar o alterar la religión de mi crianza--ahí estaba a gusto.
Pero al retirarme frecuentemente a una comunión secreta
en mi propio corazón y estar quieto,
fui llevado poco a poco a una estrecha confianza y dependencia de la instrucción divina,
sin considerar que algún otro cuerpo de Cristianos
hiciera esta profesión más abiertamente que yo.
La Divina misericordia me veía en ese momento,
como había visto a Natanael bajo la higuera cuando nadie más lo veía,
y me permitió probar mi propia fuerza al esforzarme por establecer mi propia justicia,
para que al sentirme superado en la contienda contra el hombre de pecado,
pudiera someterme más fácilmente cuando llegara el
momento de pedir y recibir fuerza de Aquel,
'`sobre el que está puesto nuestro socorro.`'^
footnote:[Salmo 89:19]

Yo solía presentar mis peticiones por la mañana y por la noche,
rogando que fuera preservado de las tentaciones y del pecado,
y muy frecuentemente leía algunas porciones de la Escritura antes de ir a la cama.
La semana anterior al culto en el que recibiría los elementos,
solía leer el rito previsto para ello,
y vigilaba cuidadosamente mis palabras y mi carácter para
poder recibir el rito con cierto grado de aceptación. Pero
a menudo me sorprendía que no sintiera ninguna fuerza adicional,
proveniente de mi muy constante asistencia al culto público y al sacramento (así llamado),
habiendo leído y oído hablar de los efectos beneficiosos
que se obtenían por recibir el pan y el vino.
Porque en esas ocasiones (que eran muy solemnes para mí),
cuando me retiraba de lo que llamaban la mesa del Señor,
y humildemente me arrodillaba en la banca para agradecerle a Dios,
y pedirle que bendijera los elementos para mi regeneración, mis oraciones,
incluso entonces,
parecían ser secas y carentes de los frutos que yo había aprendido a esperar de ellas.
Todo eso era realizado en mi propia fuerza--yo decía: "`Seré sabio;
pero la sabiduría se alejó de mí`"^
footnote:[Eclesiastés 7:23]--el cabello que era por naturaleza
negro no se había hecho blanco por ese medio,
ni lo que estaba torcido se había hecho recto.
En lugar de que el viejo hombre fuera más crucificado que antes,
los enemigos de mi propia casa se mantenían en posesión; sin embargo,
puedo decir que sus bienes no estaban en paz, porque yo anhelaba que fueran expulsados,
y ser liberado de la ley del pecado y muerte,
bajo la cual yo gemía y me esforzaba por vencer.

Yo tenía una irritabilidad natural en mi disposición, la cual,
tenía muchos deseos de vencer,
ya que perturbaba mi mente de ese estado de tranquilidad en el que encontraba reposo;
pero todo el cuidado que empleaba para someterla, a veces no era suficiente,
y era motivo de gran inquietud para mí cuando brotaba.
Sin embargo,
gracias al favor divino podía tener una buena apariencia externa ante los hombres,
no era culpable de inmoralidad, se me consideraba sobrio y religioso,
y sobre esta base tenía una muy buena opinión de mis propios logros.

Estaba listo a establecerme ahí y a pensar que había
alcanzado el deseado remanso de reposo;
pero creo que ese estado es una de las sutiles artimañas de nuestro gran adversario,
y es un falso reposo, y no el reposo preparado para el pueblo de Dios.
En ese falso reposo el enemigo no nos molestará;
nos permitirá permanecer ahí toda la vida,
como me temo que sucede con muchos--y al descansar en sus propias labores,
sus obras no los seguirán. Pero mi misericordioso Redentor,
quien conocía la integridad de mi corazón y veía que ese pan no satisfacía
a mi alma hambrienta (porque yo tenía hambre y sed de justicia,
la que esas cosas no producen),
le plació visitarme una y otra vez mediante secretos toques de Su Santo Espíritu,
atrayendo poco a poco mi atención hacia ellos, temporada tras temporada,
haciéndome conocerlos como una luz en mi oscuro corazón,
y como un reprendedor y pronto testigo contra toda aparición del mal.
Le prestaba atención a esa luz y me regocijaba en ella,
pero debo decir que no la conocía entonces como he llegado a conocerla.
Creía que era divina,
pero como mi mente estaba muy limitada por los prejuicios de mi crianza
a favor de la profesión religiosa que me habían enseñado a creer,
no buscaba, ni esperaba sentir _en mí mismo,_
la segunda venida de nuestro Señor Jesucristo sin relación con el pecado para salvación.^
footnote:[Hebreos 9:28]

Mis puntos de vista y expectativas eran externos,
mi adoración sólo era en el atrio exterior, el que era hollado por el espíritu gentil.^
footnote:[Apocalipsis 11:2]
Yo lo buscaba a Él afuera,
a quien mi alma secretamente deseaba encontrar--al Salvador que
había prometido salvarnos _de_ nuestros pecados y no _en_ ellos.
El pecado había llegado a ser tan sobremanera pecaminoso en mí,
que mi clamor a veces era: "`¡Un Redentor o perezco!`"
Pero no Lo hallaba, porque estaba buscando Al que vive, entre los muertos,
y la ley externa no podía perfeccionar a los que se acercaban.
Aquel que yo buscaba había resucitado,
y se acercaba el día en que esas formas y sombras vacías debían huir.
Todos los esfuerzos en mi propia fuerza, voluntad y sabiduría resultaban ineficaces,
pero el Sol de Justicia estaba surgiendo entonces con salvación en Sus alas,
para producir en mí la vida que está escondida con Cristo en Dios.
Y cuando el día del poder del Señor llegó sobre todas las cosas
en las que yo pensaba mucho--como mis logros en una vida y conducta
religiosas--ardió como un horno y consumió todo lo de esa naturaleza,
para que sólo el Señor gobernara y reinara en mi corazón, de quien es el derecho.
Mi justicia parecía ser como trapos de inmundicia,
y no era suficiente para cubrir mi desnudez.
Entonces pude decir con el santo Job: "`'`Desnudo vine al mundo y desnudo saldré,`'^
footnote:[Job 1:21]
y a menos que Tú, oh, Señor, me cubras con un vestido nuevo,
esta cubierta de hoja de higuera no podrá esconderme de Tus juicios`"--cuyos
juicios empezaron entonces a ser revelados en mi alma.

Durante años había tenido la costumbre de ir ocasionalmente a las reuniones de los Amigos,
pero conforme mi espíritu empezó a anhelar más riquezas
duraderas que las que ya había obtenido,
asistí más frecuentemente a ellas; sin embargo,
no puedo decir que me sintiera muy beneficiado por ello.
Porque,
aunque sabía que el pueblo llamado Cuáqueros profesaba una
religión más espiritual que otros pueblos en esta tierra,
no era capaz entonces de formar un justo juicio de
eso que sólo había oído por el oído externo.
Mi ojo espiritual no había sido ungido entonces,
el único por el que habría podido ver las maravillas de la nueva creación de Dios,
en y a través de Su querido Hijo Jesucristo.
No había llegado aún el momento en el que el Señor entraría a Su templo,
y la tierra sería conmovida por Su divina presencia, quien en verdad,
¡es el Señor de toda la tierra, y digno de ser temido, honrado y obedecido!

Mientras me encontraba en este estado de ánimo de búsqueda,
asistí a la Reunión Provincial celebrada en Lurgan.
En la primera sesión un Amigo habló de esta porción de la Escritura: "`He aquí,
yo estoy a la puerta y llamo; si alguno oye mi voz y abre la puerta, entraré a él,
y cenaré con él, y él conmigo.`"^
footnote:[Apocalipsis 3:20]
No encontré que ese testimonio produjera algún buen efecto en mí,
porque yo había sido edificado sobre una buena opinión
de la profesión religiosa de mi crianza,
ni vi mucho en las vidas y conductas de muchos entre los Cuáqueros,
que me indujera a darles más preferencia sobre mis compañeros profesantes.
Más aún, no comprendía la naturaleza o uso de las reuniones en silencio.
Había allí un Amigo de Pensilvania llamado Robert Willis,
que creo que en esa sesión se mantuvo en silencio.
Cuando los Amigos se reunieron en la Reunión de Disciplina,
entré sin saber lo inapropiado de eso; y aunque había porteros,
ellos me dejaron pasar al observar una solemnidad en mi semblante.
Durante la pausa de silencio Robert Willis habló. Qué dijo, no puedo decirlo,
porque mi mente estaba reunida en un silencio interior,
pero un poder tal irrumpió en mí que rompí a llorar,
y sacudía todo mi cuerpo de forma extraordinaria,
acompañado por el sentimiento de la vida divina que se levantaba
dentro de mí. Y aunque un espíritu de juicio brotó con ella,
aun así dejó una virtud sanadora,
de modo que pensé entonces que no me avergonzaría confesar la Verdad en la vía pública,
por muy grande que fuera la vergüenza.
En ese momento la cruz era nada para mí,
comparada con el tesoro que había encontrado escondido
en mi corazón. Yo estaba determinado a venderlo todo,
para poder ganar la perla que por tanto tiempo había buscado en vano entre la basura.
¡Oh, recuerdo ese día, cuánto me regocijé! ¡Un nuevo canto fue puesto en mi boca,
alabanzas a mi Dios!

No espero otra cosa sino que esta afirmación sea tildada de entusiasmo^
footnote:[En esa época la palabra _entusiasmo_ era usaba con
frecuencia para referirse al fanatismo o emocionalismo religioso.]
(o los efectos de una imaginación perturbada o calenturienta),
por los que nunca han pasado en sí mismos la misma experiencia
feliz y bendita que yo llamo (con respecto a mí mismo),
el comienzo de la nueva creación de Dios en Cristo Jesús. El evangelio,
en los días de los primeros mensajeros,
fue denominado "`locura`" por los sabios y prudentes del mundo.
A un notable predicador del evangelio se le dijo,
que '`las muchas letras lo habían vuelto loco.`'^
footnote:[Hechos 26:24]
En efecto, sus vidas eran consideradas una locura,
porque la vida que ellos entonces vivían era en Cristo Jesús,
mientras que la vida de los que los condenaban era según la carne,
satisfaciendo los deseos de la carne.

Por un lado, me temo que hay muchos que profesan creer en estas cosas conmigo,
y sin embargo, no las comprenden verdaderamente; porque no tenemos nada bueno,
sino lo que nos es dado por Dios, y si no nos preocupamos por pedirle sabiduría,
no la recibiremos, porque la promesa sigue siendo para los que piden.
Algunos entre nosotros sí piden, pero piden mal,
pidiendo algo de la forma externa que esta no puede dar.
A estos estados no los trataré de convencer de su error usando algún razonamiento,
habiendo experimentado en mí mismo, cuán difícil, no, puedo decir,
_cuán imposible_ habría sido convencerme de esas verdades
antes de que la divina misericordia me fuera extendida.
Pero Él, mediante una simple operación de Su poder
(comparable al lodo y a la saliva)
abrió mis ojos ciegos, de manera tal,
que me permitió ver la luz de Su glorioso semblante y de confesarlo delante de los hombres.
Sin embargo, escribo estas cosas para los caminantes, hombres y mujeres,
que viajan a Sion y que pueden leerme en sus propias experiencias,
para animarlos a permanecer en sus caminos,
y a no dejar que el desánimo que puedan encontrar en su viaje por el desierto,
los haga volver su mirada a Egipto;
porque sólo los que resistan hasta el final serán salvos.

En ese entonces estaba muy reducido al silencio,
y mi espíritu a menudo se volvía al interior,
esperando y velando en pos de Aquel a quien mi alma amaba.
Pensaba,
que habiendo encontrado a Aquel de quien Moisés y los profetas escribieron--cuyo
bendito día vio Abraham en la visión de la vida y se alegró,
y cuya sangre rociada habla mejores cosas que la de Abel--la
esclavitud egipcia de pecado había llegado a su fin;
lo cual, tal vez fue el caso con el Israel de antes,
cuando Moisés les llevó el mensaje del Dios de sus padres,
ordenándole al faraón que dejara a Israel ir y adorar a su Dios.
Pero el faraón espiritual no iba a ser tan fácilmente vencido como yo pensaba.
Cuando él se enteró de que yo estaba por salir de debajo de su gobierno,
y viajar hacia la tierra prometida,
sometiéndome día tras día a la guía de la nube durante el día,
y de la llama brillante durante la noche, fui estrechamente perseguido por él,
sus jinetes y sus carros, como si hubiera decidido que yo no escapara de ellos.
El poder con el que se les permitía probarme era grande, tanto así,
que yo pensaba que no había un poder más grande,
al no haber experimentado aún la venida de Aquel que era más fuerte que ellos,
revestido con el poder de Su Padre, para despojar al hombre fuerte de sus bienes,
echarlo y tomar posesión para Sí mismo.
Esta es la obra de regeneración,
muy poco conocida por los profesantes del Cristianismo de mentalidad mundana.
Estas son las buenas nuevas del evangelio (el poder de Dios),
que predica y enseña la libertad a los cautivos,
y abre las puertas de la prisión a los que han estado
atados por las cadenas de oscuridad y pecado.
Esta no es la obra de un día,
o de un año--tal vez sea la obra de la mayor parte de nuestras vidas,
avanzando hacia la perfección como declaró el apóstol Pablo '`no
que ya seamos perfectos;`' aunque él había predicado el gran y
aceptable año del Señor en Arabia y en las naciones de alrededor.
Por tanto,
el mandamiento de nuestro Señor y Maestro debe ser
recordado en cada etapa de nuestro viaje,
"`velad y orad.`"^
footnote:[Mateo 26:41]

¡Oh, los terrores que me rodeaban de día y de noche,
para que el enemigo no me dominara ni me llevara de regreso a la casa de servidumbre,
ahora que había sido hecho partícipe (en alguna medida)
de la gloriosa libertad de los hijos de Dios!
Se me presentaba una tentación tras otra,
algunas en la sabiduría y astucia de la serpiente,
y otras en los rugidos blasfemos de un león que eran espiritualmente
pronunciadas en mi oído. Pero descubrí por experiencia,
que mi paz y mi seguridad se encontraban en el profundo retiro de espíritu y en el silencio;
y aunque el sutil adversario sólo había venido a matar y a destruir,
sus aguas movían el molino de Dios y me dirigían a casa,
a buscar ayuda donde está puesto el socorro;
y a su debido tiempo lo encontraba ahí. Profundos, en verdad, eran mis conflictos,
tanto que me sentía dispuesto a intercambiar condiciones con los trabajadores pobres,
si hubiera podido encontrar la paz con Dios y la remisión de los pecados pasados.

En el mes Once de 1772, asistí a la Reunión de Medio Año en Dublín. En ese momento,
yo no había hecho ninguna alteración en mi vestimenta o apariencia,
que era más o menos la acostumbrada por la gente.
En una de las reuniones de adoración sentí mi mente atraída a un
profundo silencio--toda consideración externa pareció retirarse,
y una profunda solemnidad cubrió mi espíritu, a la que me rendí en gran medida,
habiendo encontrado en algunas ocasiones, que mi fuerza era renovada por ello.
En ese momento Robert Willis se puso de pie, y qué dijo, no lo supe entonces,
ni lo he sabido después,
pero sentí que mi estado y mi condición perdidos fueron expuestos
de tal manera delante de mí en lo secreto de mi alma,
que con angustia clamé por misericordia.
Verdaderamente pensé que el pozo estaba abierto y listo para recibirme,
y que todos los horrores de este me rodeaban.
Esta visita de juicio, con los terrores que la acompañaron,
me llevó muy profundo y bajo en mi mente, sin embargo,
encontré que el temor divino operaba como una fuente de vida,
preservándome de las trampas del pecado y de la muerte
más que los muchos años de "`culto voluntario`"^
footnote:[_Culto voluntario_ es un término usado para referirse
a cualquier forma de adoración acorde con la voluntad,
tiempo y recursos del hombre. Ver Colosenses 2:23]
que había practicado anteriormente.
Entonces podía decir, por una temible experiencia, que mi Redentor vivía,
y que era un Dios cercano y no lejano,
y que era muy limpio de ojos como para contemplar el pecado de cualquier tipo,
con algún grado de aprobación. Regresé a casa muy humillado,
y con frecuencia estaba en retirado silencio,
y diligentemente escudriñaba las Escrituras para
encontrar algún alivio para mi atribulada mente;
y puedo testificar que ellas son las Escrituras del Espíritu de Verdad,
dadas por hombres santos de antaño según fueron inspirados por el Espíritu Santo;
porque descubrí al mismo Espíritu divino dando testimonio de ellas en mi espíritu,
y revelándome consejo e instrucción para mi edificación y consuelo.

Fue entonces cuando los juicios del Señor fueron revelados en mi tierra,
para que así aprendiera justicia.^
footnote:[Isaías 26:9]
Todos mis pecados y transgresiones, que eran muchos,
fueron puestos en orden delante de mí;
como si un libro de memoria hubiera sido guardado en lo alto,
y que nada había sido olvidado.
¡Oh, los terrores de aquellos días, cuando el Juez justo de la vida y de la muerte,
revestido de una terrible majestad y poder, se sentaba a juzgar en mi alma,
quien no sólo escudriñaba las cosas más ocultas (mostrando
que nada puede escapar de Su ojo que todo lo ve),
sino que me hacía sentir vivamente, que también tenía el poder de arrojar al infierno!
Un día emitía palabra a otro día, y una noche a otra noche declaraba sabiduría,
de que no había arrepentimiento en la tumba,
y que el arrepentimiento y la remisión debían ser hechos en estos cuerpos.
Por horas he estado de rodillas con las manos alzadas, pidiendo misericordia,
y a veces aparentemente llevado al borde de la muerte
eterna antes de poder sentir la remisión de pecado.

Mi deber para con mis padres fue puesto bajo escrutinio,
y con gran temor tuve que hacer una indagación minuciosa; porque ambos estaban muertos,
y entonces no tenía la posibilidad de compensar los errores pasados.
Pero en cuanto a esto,
tuve la pacífica respuesta de que nunca los había afligido voluntariamente,
o comportado indebidamente con ellos.
¡Oh, hijos, permítanme suplicarles, en el temor del Señor,
que '`obedezcan a sus padres en el Señor, porque eso es justo`'^
footnote:[Efesios 6:1]
ante Su santa vista; y ustedes que actúan de manera ligera o descuidada con sus padres,
y los afligen con sus conductas desobedientes,
estoy persuadido de que tendrán que responder de ello en este mundo, o en el venidero.

Ahora bien,
hablar sobre un tema en el que una gran cantidad de personas
(a quienes prefiero por encima de mí mismo,
en cuanto a conocimiento adquirido y entendimiento natural) ponen gran dependencia,
es muy difícil para mí; sin embargo, no puedo sentirme en paz,
si no relato mi experiencia con respecto a la profesión religiosa formal que practiqué,
cuando todas mis obras de justicia (así llamadas) e injusticia fueron
llevadas delante del gran tribunal que estaba establecido entonces en
mi corazón. Vi que cuando la verdadera iglesia huyó al desierto,
y el gran dragón rojo arrojó tras ella sus torrentes de persecución,
había un lugar preparado para ella ahí, por un tiempo, tiempos y la mitad de un tiempo.^
footnote:[Apocalipsis 12:1-7]
Fue entonces que la sabiduría de los hombres tomó dominio,
y se sentó como anticristo en el templo del corazón del hombre,
donde antes se había sentado y gobernado Cristo como la Cabeza de Su iglesia.^
footnote:[2 Tesalonicenses 2:3-4]
Entonces apostataron de la verdadera fe, que era el don divino de Dios para Su iglesia;
y tras haber perdido la luz en las tinieblas del entendimiento humano,
establecieron una forma de piedad, al negar el único poder que puede producirla.
Y en lugar de la fe verdadera y viva que '`había sido una vez dada a los santos,`'^
footnote:[Judas 1:3]
establecieron credos y formas de oración que se ajustaban a cada estado y condición,
apartando así a las personas de sentir sus propios estados y condiciones,
tal como realmente eran ante los ojos de Dios.
Y aunque los hombres, a lo mejor se sentían secretamente juzgados por esas cosas,
habían sido enseñados a confiar en las oraciones y súplicas
preparadas para ellos cien años antes de que nacieran;
incluso cuando el Espíritu divino (que no quiere la muerte
del que muere) estaba listo para hacer intercesión por ellos,
no con una forma establecida de palabras adecuadamente unidas,
sino con suspiros y gemidos que nadie más podría pronunciar por ellos.

En cuanto a las oraciones preestablecidas,
que son presentadas ante el trono de la gracia por el hombre no regenerado,
que está en un estado de depravación moral--estoy persuadido de que son una abominación
para Dios y que no obtendrán Su aceptación. '`Hagan primero el árbol bueno,
y el fruto será bueno también;`'^
footnote:[Mateo 12:33]
sin embargo, sólo Cristo, el buen Labrador, puede hacer que el árbol sea bueno,
y entonces comerá del fruto.
Yo practicaba por la noche y por la mañana,
decir oraciones preestablecidas en la forma más humilde
que sabía. El Señor soportó eso en los días de mi ignorancia;
pero cuando vi en la luz cuán inaceptable era para Su santa vista
el '`culto voluntario,`' y que en muchos aspectos lo había abandonado,
con todo, continué por un tiempo en esa práctica.
Una noche, mientras estaba arrodillado, sentí que se apoderaba de mi tal terror,
que me levanté rápidamente y nunca más me atreví a orar de la misma manera.

Cuando la verdadera iglesia salió del desierto (lo que ha hecho en estos últimos días^
footnote:[Hace referencia a un regreso a la vida y pureza del Cristianismo
primitivo experimentado por muchos en la primera Sociedad de Amigos.]),
salió apoyándose en el pecho de su Amado--habiendo dejado de lado
todas las formas y ceremonias inútiles que no aprovechan,
y dependiendo únicamente de las directas enseñanzas de la
gracia de Dios y de las revelaciones de Su Espíritu Santo.
De esta forma, el anticristo fue despojado de su dominio y gobierno en la iglesia,
y Cristo tomó para Sí, Su propio poder y autoridad para dominar y reinar, quien además,
nombra a Sus propios siervos y los capacita para los varios
usos y propósitos que Él (en Su santa sabiduría) ha asignado,
enviándolos y diciéndoles: "`De gracia recibisteis, dad de gracia.`"
Estos no buscan la plata, el oro, ni el vestido del hombre,
sino que suplen sus propias necesidades y las de otros,
con el trabajo de sus propias manos.

Aunque yo, según creía, había sufrido profundamente en la hora del juicio y del fuego,
esas cosas que había sufrido sólo eran el principio de dolores.
El terreno del corazón no debía ser removido superficialmente.
No, era necesario introducir el arado del evangelio, romper el terreno no labrado,
y no sembrar más entre espinos.
Los terrores de los juicios de Dios a menudo eran puestos delante de mi mente,
y me causaron impresiones tan profundas,
que creo que nunca se borrarán. Es una verdad más allá de toda contradicción para mí,
que el Espíritu divino no morará en un templo que
Él no haya limpiado previamente en gran medida.
Ahora les hablo a ustedes, queridos hermanos y hermanas,
que han conocido en sus propias experiencias sus medidas de las profundidades de Satanás,
que han sido sacados de Egipto con una mano fuerte y un brazo extendido,
y han experimentado que el bautismo de Cristo es con fuego y con el Espíritu Santo.
Este es el único bautismo que proporciona "`testimonio
de una buena consciencia delante de Dios,`" ^
footnote:[1 Pedro 3:21 RVG] y limpia tanto la carne como el espíritu.

Puede que en este momento,
no sea necesario relatar más de los inescrutables juicios de Dios,
que no se pueden descubrir sino por la experiencia de estos.
Puedo decir que, "`un día emite palabra a otro día,
y una noche a otra noche declara sabiduría.`"^
footnote:[Salmos 19:2]
La tranquilidad siguió a esas terribles voces pronunciadas desde el monte,
las cuales no llegaron a través del hombre ni por el hombre; de hecho,
en esas cosas el hombre no tuvo participación o porción. La remisión
de pecados pasados pareció ser pronunciada en ese estado de quietud,
y una voz dijo: "`Vete, y no lo hagas más.`"

Entonces fui llevado a la escuela de Cristo,
para ser instruido por Él en esa ley interior que iba a ser el gobierno de mi vida futura.
El vino viejo fue derramado, los cielos viejos fueron enrollados como un pergamino,
y yo voluntariamente los entregué al fuego.
No consulté más con '`carne y sangre,`' sino que me rendí
a la visión celestial e incliné mi oído a la instrucción,
porque Él hablaba ahora como "`jamás hombre alguno ha hablado.`"^
footnote:[Juan 7:46]
En lugar de "`afilar Su reluciente espada y echar mano del juicio,`"^
footnote:[Deuteronomio 32:41]
se convirtió en mi Pastor,
y mediante el cayado de Su amor me persuadía a seguirlo en el nuevo camino,
llevándome a veces a delicados pastos y refrescando mi pobre y desconsolada mente.
Entonces pensé que correría alegremente por el camino de Sus mandamientos
y que nunca me cansaría. De buena gana habría hecho mi tabernáculo ahí,
pero tuve que bajar de la montaña y pasar la estación de invierno,
y llorar la ausencia de Aquel a quien mi alma había sido enseñada a amar,
pues el olor de Su ungüento era delicioso para mí.

La misma Semilla divina de luz y vida que me condujo fuera de las
formas y ceremonias para adorar al Padre en Espíritu y en verdad,
también me condujo mediante sus secretas enseñanzas por un camino recto y estrecho,
con respecto a todos los excesos en el vestir y el hablar;
y el mismo poder me ha preservado en él hasta hoy,
y confío en que lo hará hasta el final--porque en Él no hay mudanza
ni sombra de variación. La sencillez en el vestir y el hablar es
apropiado para un humilde seguidor de un Salvador crucificado.
Muchos encuentran una cruz en la práctica de estas cosas,
porque ellas abiertamente declaran a otros de quién somos discípulos.
Los hijos del mundo, en sus necios y vanos corazones,
desprecian la sabiduría de Dios en estas pequeñas cosas,
las cuales tienen la intención de crucificarnos al espíritu del mundo,
con toda su pompa y vanidad.
Estos se avergüenzan de la cruz y prefieren disfrutar de los placeres
de un mundo pecaminoso (que son sólo por una temporada),
que sufrir la aflicción con el pueblo de Dios por las burlas de los hombres.
Aunque yo sabía que los Cuáqueros sostenían estos testimonios,
y que eran marcas externas de comunión con ellos,
aun así yo deseaba ver y conocer el fundamento de ellos en mí mismo,
y no abrazar algo de tan grande importancia,
excepto por una clara convicción que procedía del
Fundamento vivo que Dios había puesto en mi corazón,
y no del hombre.

La práctica y el uso de un lenguaje sencillo,
son consistentes con las reglas de la gramática y
del lenguaje de los hombres santos de antaño,
como lo atestiguan las Escrituras; sin embargo, yo deseaba probar todas las cosas,
llevarlas al estándar de la verdad en mi corazón, y si soportaban la prueba,
entonces aferrarme a ellas.
Durante mi estado de infancia espiritual, a veces usaba este lenguaje y a veces no.
Oí que mis parientes cercanos decían que yo estaba fuera de mí, y por lo tanto,
era una cruz hablar de esta manera en presencia de ellos.
Pero negar la cruz trajo tristeza y debilidad,
y también el temor de que si yo bajaba los peldaños de la escalera de Jacob,
me resultaría más difícil recuperar el terreno que había perdido que ascender
otro peldaño. La perspectiva de la gloriosa corona de justicia que estaba
delante de mí como alcanzable a través de la fidelidad,
me animaba a seguir adelante; y en la medida que me esforzaba por hacerlo,
así me fortalecía, el yugo se hacía más fácil y la carga más ligera.
Y cuando inadvertidamente ocurría una omisión (porque después
de ese tiempo nunca me atreví a transgredir voluntariamente),
siempre me sentía herido en mi espíritu.

El cambio en mi vestido fue una gran cruz,
dado que siempre había sido dado a la ropa de moda,
y en ese momento tenía varios trajes de ese tipo.
Una mañana temprano, mientras estaba en la cama,
sentí que una solemne cubierta se apoderaba de mi espíritu,
la cual me llevó a un profundo silencio y atención. Entonces sentí que se requería
de mí conformarme a la apariencia simple de los seguidores de Cristo.
Su vestido era de una sola pieza; así debía ser el mío--de una sola pieza con mi hablar,
mi vida y mi conducta.
Esto me pareció un duro golpe; porque ya no me quedaba ningún refugio,
sino que debía parecer un tonto para el mundo.
Mi hablar y luego mi vestimenta, delatarían que yo había estado con Cristo,
y que profesaba ser uno de Sus discípulos.
Lloré amargamente,
y argumenté que la cruz sería muy pesada para mí delante de mis amigos y conocidos,
y que la pérdida me resultaría muy grande al dejar la ropa que tenía en ese momento;
pero el Señor guardó silencio ante mis quejas,
y la levadura obró en la masa hasta que todo el hombre fue leudado en sumisión. Entonces
corrí el camino de Sus mandamientos con gozo y presteza de corazón,
tanto así que he escuchado de pasada a algunas personas
decir que jurarían que yo era un Cuáquero.
"`¡Ojalá,`" dice mi espíritu, "`que toda la familia de Dios fuera tan notoria, es decir,
en el exterior, para que así pudiera ser claramente visto a quién sirven!`"

Otro testimonio que sostenemos es que no podemos, con buena consciencia,
contribuir de ninguna manera con el sostén del ministerio de ninguna
iglesia que obtenga su mantenimiento de sus servicios en el altar.
Porque nosotros creemos en este día,
que Cristo es la cabeza de la verdadera iglesia militante,
y que la promesa que hizo antes de ascender a Su Padre:
"`He aquí yo estoy con vosotros todos los días, hasta el fin del mundo,`" se cumple,
al sentirse Su divina presencia dondequiera que dos,
tres o más de Sus hijos vivos estén reunidos en Su nombre.
Al ser esta una verdad que creemos plenamente,
nos hace expresamente conscientes de que Él (la Cabeza de este
cuerpo) todavía capacita y envía siervos y siervas a ministrar;
primero, preparándolos para Su obra y servicio por medio de varias dispensaciones,
bautismos y lavamientos espirituales, y luego,
entregándoles el pan que Él ha partido y bendecido,
para que tengan pan para darle a la multitud, sin ninguna adición propia.
Y estos, sabiendo en quién han creído,
ni pagarán ni recibirán salarios de ningún hombre como el precio de su labor;
porque están persuadidos de que Aquel a quien sirven es fiel y verdadero,
y habiendo recibido sus ministerios sin honorarios ni recompensas, de gracia lo dan,
esperando la recompensa de Aquel que los envió, que es la gavilla de paz en sus senos.

Al leer este relato, algún incrédulo puede preguntar,
¿cómo sé que el sutil adversario no se ha vestido como ángel de luz y me ha engañado?
Le respondo a tal persona con las palabras de nuestro bendito Señor,
que son las palabras de la Verdad: "`Mis ovejas conocen mi voz, y me siguen,
mas a las voz de un extraño no seguirán.`" Además,
se nos ha dicho que sigamos aquellas cosas que contribuyen a la paz,
y a la mutua edificación.^
footnote:[Romanos 14:19]
En realidad, nunca he encontrado otra cosa que no sea paz,
como consecuencia de la obediencia inquebrantable en estos aspectos.

He dado ya un breve relato de la razón que tuve para unirme en comunión
religiosa con aquellos con los que he continuado caminando desde entonces.
Y aunque he sido objeto de muchas burlas y escarnios por parte de algunos de mis parientes,
así como también de muchos otros,
he sido misericordiosamente capacitado para no apartar mi mejilla del golpeador,
sino de soportarlos por la causa de Aquel que sufrió
más y peor por hombres pecadores y perversos.
Me regocijo y le doy gracias a mi misericordioso Redentor,
porque en Su misericordia me ha llamado de las costumbres que había recibido,
y me ha dado una porción en Su servicio y comunión con Su pueblo.
Escribo estas cosas con la esperanza de que sean de bendición
para los viajeros que transitan por la misma calzada,
para que se conviertan en señales en el camino para ellos,
y muestren así que este no es un camino intransitado,
sino que otros lo han recorrido antes que ellos y han encontrado seguridad.

En algunas de estas épocas de profundo bautismo antes relatadas,
solía extenderse en mi mente que el Señor tenía un servicio para mí,
para hacer uso de mí en Su iglesia y familia.
Esto traía un gran temor sobre mi mente,
no fuera que Satanás (cuyo poder de engaño yo conocía ya considerablemente)
se hubiera vestido con la apariencia de ángel de luz y me hubiera engañado,
y así, yo me convirtiera en una vasija estropeada en la rueda.
La preparación del corazón en el hombre,
y la respuesta de la lengua en este arduo asunto, deben ser del Señor únicamente.^
footnote:[Traducción literal de Proverbios 16:1 en la versión King James]
El hombre debe renunciar a su sabiduría,
y someter a la dirección divina su conocimiento adquirido,
y sólo conservar aquellas habilidades que la divina
sabiduría vea adecuadas para hacer uso de ellas,
aunque nos haga parecer tontos ante los que antes pensaban lo contrario de nosotros.
Sin embargo, este estado bajo nos es dado en misericordia, para humillarnos,
para que no dependamos de nada propio, ni del anterior conocimiento de doctrinas,
a menos que las sintamos renovadas en la vida y el Espíritu,
para que de este modo todos nuestros manantiales frescos en y para el servicio,
estén en Aquel que es nuestra Cabeza y santo Sumo sacerdote.

¡Cuántas humillaciones son necesarias para llevarnos a la norma
donde Dios se complace en enseñar Sus caminos! ¡Cuán indispuestos
están muchos a acercarse a dicha norma o a ser medidos por ella!
Pero cuando Sus justos juicios están en la tierra, es entonces, y sólo entonces,
que estamos dispuestos a aprender justicia.^
footnote:[Isaías 26:9]
En esta importante posición puede decirse, que Él conduce a Israel como un rebaño,
y que con frecuencia los lleva a delicados pastos
y hace que reposen ahí a mediodía. Esto,
en realidad,
es un gran misterio que el profesante de religión de mente mundana no conoce, ni puede,
porque sólo es discernido espiritualmente por aquellos para quienes es preparado.
Este fue el caso de los discípulos de antaño, cuando se les dijo:
"`A vosotros os es dado conocer los misterios del reino de Dios;
pero a los otros por parábolas.`"
^
footnote:[Lucas 8:10] Los verdaderos ministros salen "`sin bolsa y sin alforja,`"^
footnote:[Lucas 22:35]
no dependen de nada más que del llamado del presente servicio.
Ellos no creen que sus experiencias anteriores,
o la simple aprobación de sus hermanos y hermanas (la imposición de manos de los ancianos),
sean calificación suficiente para oficiar en la iglesia.
En lugar de eso esperan la unción fresca, y si no se les proporciona,
entonces guardan silencio y continúan esperando ceñidos a Su Señor y Maestro,
hasta que Él sea servido.^
footnote:[Lucas 17:8]
Estos siervos bautizados son tan celosos del honor de su Señor,
que ni buscan ni reciben salarios de ninguna otra mano, sino de la de Él. De hecho,
están dispuestos a gastar lo propio y a gastarse en salud y fuerzas en Su servicio,
sabiendo que cuando Él venga, Su recompensa de paz estará con Él.

Después de estar unos dos años en esta escuela de experiencia religiosa,
en la que yo creía haber adquirido alguna destreza,
y al sentir un grado de la justificación que viene
después de la dispensación de condenación (la que también tenía su gloria),
pensé que se había acercado el tiempo en que debía ser llamado
a invitar a otros a venir y probar por sí mismos,
cuán bueno es el Señor con aquellos que lo aman y le temen.
En las reuniones, solía sentir a veces,
a la Palabra de Vida morando en mi corazón,
con un caudal de lenguaje vivo que parecía estar dirigido a varios estados presente,
pero no me atrevía a pronunciarlo con palabras;
y no recuerdo haber sentido ninguna condenación por no hacerlo en ese momento.
En la administración de mis asuntos externos, en el huerto y en los campos,
a veces sentía un lenguaje vivo en mi corazón,
como si me estuviera dirigiendo a una asamblea de personas.
Esto solía comenzar tan imperceptiblemente para mí,
que se movía o fluía en mí por algunos minutos antes de que yo le prestara atención;
pero cuando lo hacía, se incrementaba tanto como para burbujear como un manantial,
lo cual me hacía romper en lágrimas y dejaba un dulce
sabor de paz y consuelo detrás. Estos,
creo, eran sólo los primeros frutos del Espíritu,
y como un ministerio de preparación para la importante obra del ministerio.

Me temo que algunos han confundido esta preparación con la obra misma, por tanto,
han nacido antes de tiempo,
y no han llegado a ser de la utilidad y servicio en la iglesia para lo que fueron destinados.
El profeta Elías (creo) fue probado con una experiencia similar en el monte,
pero fue salvado misericordiosamente de salir de la cueva,
antes de escuchar al "`silbo apacible y delicado`" preguntarle claramente,
por qué estaba allí. Para algunos el fuego es demasiado caliente y se alejan
de la hora de los juicios de Dios antes de que la vasija esté completamente seca.
Estos no pueden contener el vino nuevo, quedan agujereados,
y permiten que corra y se derrame para perjuicio de la familia de Dios
y para su propio gran daño. Los tales deben regresar a la casa del Alfarero,
ser puestos en la rueda y aprender a ser como la arcilla pasiva,
dispuestos a ser formados y moldeados en cualquier vasija
que el gran Alfarero considere adecuado para Su propio uso.

Luego, las expectativas de servicio en la iglesia se desvanecieron,
aunque recibí mucho ánimo de algunos Amigos con quienes
viajé en sus servicios por la Verdad,
así como también por medio de las cartas de otros;
pero tales ánimos nunca me hicieron ejercer un don que no había
recibido aún. Yo era extremadamente cuidadoso conmigo mismo,
para no ser una vasija estropeada en la rueda.
Por tanto, cubriendo mi cabeza con mi manto,
esperé el "`silbo apacible y delicado`" que llegó (creo) tres años después de esto,
pero en el ínterin, no me quedé sin consuelo.
La obra de regeneración seguía adelante, y a menudo,
experiencias de la Vida eran mi porción durante mis
viajes (los cuales fueron frecuentes en esta nación),
pero creo que nunca las declaré públicamente.
Yo guardaba cuidadosamente asistir a las reuniones,
excepto cuando alguna enfermedad me lo impedía. Este
fue un deber grabado en mi mente desde muy temprano,
y creo que puedo decir,
que nunca permití que las preocupaciones del mundo se interpusieran en mi camino;
y aunque renuncié a muchas oportunidades por las que otros amasaron grandes propiedades,
yo era diligente en mi negocio, obtenía suficiente para mi familia,
y hospedaba a los extranjeros que venían a mi casa.

Pero cuando se aproximaba el momento de contarles públicamente
a otros lo que el Señor había hecho en mi alma,
este fue precedido por un largo y lúgubre viaje en el desierto, sin rocío ni lluvia,
de modo que en ese campamento estuve dispuesto a someterme a cualquier cosa,
con tal de que la nube fuera movida del tabernáculo y la
brillante llama apareciera una vez más como señal para avanzar.
Maravillosos, en verdad, son todos los caminos del Señor,
y más allá de nuestra capacidad de descubrirlos,
incluso mediante nuestras experiencias anteriores.
Se conocen sólo estando quietos para ver la salvación de Dios.
En este estado de ánimo deprimido,
fui a una reunión vecina donde iban a estar dos Amigas de Inglaterra.
En la reunión de la tarde, sentí la carga de la Palabra como un fuego,
y después de resistirla una gran parte de la reunión,
me puse de pie con las palabras que nuestro bendito Señor usó cuando lloró por Jerusalén:
"`¡Oh, Jerusalén, Jerusalén, que matas a los profetas&hellip;!`" etc.,
y luego me senté con una paz tal, como nunca antes había sentido,
que continuó el resto de la noche bajo una solemne cubierta.
Acompañé a las mencionadas Amigas en su viaje hacia el norte,
y no hablé otra vez en público por algunas semanas, hasta que llegamos a Ballymurry,
donde mi boca fue de nuevo abierta con un corto testimonio y en una debilidad tan grande,
que a menudo he pensado que apenas ha nacido alguna
vez un niño en una condición tan débil.
De hecho, tardé tanto en adaptarme a la obra del ministerio,
que durante los siguientes años,
cuando sentía la carga de ir al extranjero en el servicio de la Verdad,
me unía a algunos otros ministros viajeros, porque me sentía más seguro bajo sus alas.
En ese estado de debilidad fui tratado misericordiosamente por el Señor,
porque lo que me era dado para decir,
se repetía en mi corazón muchas veces antes de poder levantarme para comunicarlo,
y los Amigos con quienes viajaba se sentían tranquilos con mi compañía,
de modo que me aceptaban de buen grado.
Puedo decir que tenía un buen y misericordioso Amo a quien servir,
quien a menudo condescendía con el estado bajo de Su siervo y soportaba mis muchas debilidades.

Fui recibido como miembro de la Reunión Mensual de Lisburn en el año 1773,
desde ese año hasta 1775, mi mente estuvo bajo profundos ejercicios y varias pruebas,
aprendiendo la ley que está escrita en el corazón.

[.offset]
+++[+++En el año 1774, John Conran acompañó a Esther Tuke (de York) a algunas reuniones,
estando ella de viaje entonces en servicio religioso en Irlanda.
Poco después de su regreso a casa, ella le escribió a John la siguiente carta.]

[.embedded-content-document.letter]
--

[.salutation]
Estimado Amigo,

Desde que nos separamos,
te he recordado a menudo con fuertes deseos de que la estabilidad
y fidelidad sean el cinturón de tus lomos,
y la Sabiduría pura tu guía en la senda a la que confío que tus pies se han vuelto,
la cual conduce a través del desierto y el Jordán,
al establecimiento en la tierra de la promesa, la que no tengo dudas,
tú a veces has tenido a la vista.
Varias, de acuerdo con nuestras diferentes disposiciones,
son las dispensaciones que la infinita Sabiduría ve necesario
que pasemos en este viaje de Egipto a Canaán,
pero todas para este gran fin: Para reducir el yo,
purificar completamente de toda inmundicia, tanto la carne como el espíritu,
someter el mal, hacer todas las cosas nuevas y todas la cosas de Él. Grande es esta obra,
y muchos la han experimentado iniciar correctamente,
han entrado en el camino y corrido bien por un tiempo,
pero una cosa u otra los ha estorbado.
Algunos han sido como el joven que se acercó a Jesús para preguntarle,
qué otra cosa buena debía hacer, y se alejó muy triste ante la respuesta:
"`Véndelo todo.`"
En efecto, aquí está la prueba.
Todo el tesoro que tenemos--ya sea nuestra propia sabiduría, justicia,
o cualquier otra cosa--debe ser desechado, y debe experimentarse ese estado inocente,
dulce, sencillo y como de un niño, que desea la leche no adulterada de la Palabra,
para que el crecimiento sea de esa manera.
Ojalá tu crecimiento sea así, de un estado de niño, a un estado de hombre, etc.,
y entonces el gran fin del Señor al llamarte tan notablemente,
será respondido para Su gloria y tu propia paz eterna.
Porque entonces serás formado para Él y mostrarás Su alabanza.
Pero ten cuidado con las creencias y opiniones, mi querido amigo,
y con alimentarte del árbol del conocimiento;
sigue siendo el fruto prohibido que el adversario astuto y sutil presenta.
Los siervos del Señor son los pobres en espíritu, los mansos,
cuyo gozo se incrementa en Él, pero que no tienen fuerza propia--en verdad,
no tienen nada y no pueden hacer nada,
excepto cuando se les administra una fuerza fresca de Él.

[.signed-section-closing]
Tu sincera amiga,

[.signed-section-signature]
Esther Tuke.

--

Por este tiempo dos Amigas, Mary Robinson y Barbara Drewry,
llegaron aquí en el curso de su servicio religioso,
y al sentir mi mente inclinada a acompañarlas a varias
reuniones en la provincia de Ulster,
lo hice.
Luego fui con ellas a Dublín, y desde allí,
seguimos a través de las dos provincias de Leinster y Munster.
Mientras avanzábamos en nuestro viaje,
en ocasiones fuimos favorecidos con una dulce y abierta conversación,
y se nos permitió relatar muchas cosas que, según creo, fueron de provecho para cada uno.
Creo que mi querida amiga Barbara Drewry a menudo tuvo un efecto pulidor sobre mí,
y sus observaciones y correcciones sobre mis debilidades
y defectos fueron maravillosamente refrescantes y reconfortantes,
lo que hizo que no lamentara mi viaje, que fue verdaderamente satisfactorio para mí.

En nuestro camino de Ross a Clonmell, nos acompañaban varios Amigos,
algunos de los cuales me parecían como el buey desacostumbrado al yugo;
pues sus conductas, aunque inocentes, indicaban tal confusión y falta de regla,
que me producían mucho dolor e intranquilidad,
y aunque a veces tenía cuidado de mantenerme tranquilo,
aun así encontraba que sus comportamientos eran contagiosos.
En esta y otras ocasiones me he hallado muy debilitado
por estar en compañía de personas mezcladas,
especialmente con aquellas que han sentido o experimentado
poco de la disciplina del Señor en sí mismos.
Estoy dispuesto a concluir, con respecto a mí mismo,
que la conversación con tales personas se apodera de mí, y al ceder a ella (gradualmente,
y eso casi inconscientemente) en alguna medida llego a ser leudado en un espíritu similar.
Esto es causa de dolor e intranquilidad para mi alma--sentir
desorden en lugar de esa quietud,
que yo estimo ser uno de los lugares más seguros para morar.
Espero que esta observación me sea útil y produzca el efecto misericordioso
de advertirme que me abstenga de compañías mezcladas,
y de aquellos cuyas mentes nunca han sido reguladas
por la Verdad y llevadas a algún grado de orden.

He descubierto, que cuando estoy acompañado,
mi fuerza en alguna medida consiste en recordar siempre en presencia de quien estoy,
y así tener cuidado de vigilar mis labios,
para que mi conversación sea únicamente la que me está permitida.
Cuando esto es cuidadosamente atendido, a menudo estoy en silencio,
lo que creo que da fuerza, y cuando la conversación es llevada a cabo de esa manera,
es edificante y deja un sabor en la mente que es refrescante.
Por el contrario,
he experimentado que una conversación libre ocasionada por responder
a todas las preguntas hechas en tales compañías mezcladas,
conduce a la mente inconscientemente más allá de su apropiada vigilancia,
y a una variedad de temas con los que la mente regulada no tiene razón de entrometerse.
Y después de una conversación así, me he sentido reducido a debilidad,
confusión y desorden, y a veces, he estado a punto de desfallecer en espíritu.

Llegué a Dublín el 8 del mes Ocho,
donde dejé a mis queridas compañeras y regresé a mi casa.
En este viaje, no dije nada en ninguna de las reuniones,
fueran de adoración o de asuntos de orden, sin embargo,
creo que fue un tiempo provechoso para mí,
habiendo ejercitado mis facultades espirituales,
y sentido que se me proporcionaba un grado mayor de fuerza y experiencia
para soportar los asaltos y bofetadas de mi incansable enemigo.

En la reunión de medio año, en el verano,
me encontré en compañía de una joven llamada Louisa Strangman.
La primera vez que la vi en la casa de un Amigo, sentí, en silencio,
una fuerte corriente de amor hacia ella que era más que natural,
y una secreta insinuación impresionó mi mente de que ella sería mi esposa.
Escondí esto en mi corazón,
y pasaron casi dos años antes de sentirme en la libertad de revelarlo a alguien,
esperando (como comprendí) el tiempo del Señor para comunicarlo.
En ese intervalo, hubo un Amigo que la cortejó muy de cerca,
pero mis primeras impresiones me mantuvieron tranquilo bajo esta prueba.
Y cuando por fin sentí el camino abierto para proceder,
todavía pasaron cerca de seis años antes de que nos casáramos.
Esta fue una época en la mano del Señor de profundo
ejercicio y gran prueba de mi fe y paciencia,
ya que la expectativa del principio a menudo se borraba por completo; y luego,
cuando casi había desaparecido, revivía de nuevo con un grado de claridad,
para mi gran consuelo.
Resistí hasta el final,
y fui coronado con una esposa que probó ser la bendición terrenal
más rica con la que haya sido favorecido alguna vez,
una verdadera compañera de yugo, tanto en lo espiritual, como en los asuntos temporales,
y quien nunca puso un impedimento en el camino de mis servicios religiosos.
Escribo estos pocos consejos, para que en este asunto importante y de peso,
tengamos nuestra mirada puesta en la luz del Espíritu de Cristo si esperamos
ese favor del Señor--una buena esposa--quien es en verdad,
¡una corona para su esposo!

Entre los muchos desalientos de Satanás para desanimarme a abrazar el camino nuevo y
vivo que en ese entonces había sido abierto en alguna medida ante mi vista,
estaba la expectativa de grandes sufrimientos, tal vez la muerte misma;
y en esos momentos de tinieblas y sombra de muerte, la naturaleza humana retrocedía,
y a veces me sentía muy abatido y listo a decir:
"`¿Cómo permaneceré si me suceden estas cosas?
¡Temo que seguramente cederé y lo perderé todo!`"
Pero la divina misericordia fue extendida sobre mí,
al mostrarme que lo que parece imposible para el hombre, es posible para Dios.
Mientras estaba sentado en la parte de atrás en la reunión de Lisburn,
que se celebró en silencio,
sentí que el amor de Dios se extendía hacia mí de una manera tan poderosa,
que me permitió dedicar mi alma y mi cuerpo a Su servicio;
y bajo tales impresiones vivas pude decir: "`Señor, haz conmigo lo que quieras,
estoy dispuesto a sufrir la muerte por Tu nombre,`" porque entonces,
la muerte no tenía terrores para mí, el miedo a la muerte fue tragado en victoria.
Fue cuando entendí en alguna medida,
la noble postura que muchos de los mártires habían tenido, quienes,
en oposición a los tormentos a los que hombres perversos y malos los habían sometido,
se mantuvieron firmes en su integridad.
Pues sentí en la experiencia mencionada antes, cómo el Señor,
mediante Su presencia vivificante y consoladora, había estado con ellos,
así como estuvo con los tres hombre en el horno de fuego ardiente,
y los coronó con una corona de justicia, eterna en los cielos; y no sólo a ellos,
sino a todos los que aman, honran y obedecen al Señor, su justicia.

[.asterism]
'''

__John Conran continuó siendo un humilde discípulo y fiel
ministro de Jesucristo hasta su muerte en 1827,
a los 88 años de edad.
A lo largo de su larga y útil vida,
fue muy amado y estimado por los hermanos y hermanas en Cristo,
aunque siempre mantuvo una baja opinión tanto de sus logros espirituales,
como de sus servicios en la iglesia.
En una ocasión escribió: "`Mis ofrendas en las reuniones, aunque bastante frecuentes,
son muy cortas, a veces sólo unas pocas frases.
Otros queridos Amigos, a quienes yo acompaño a veces,
pueden lanzarse a las profundidades,
mientras que yo sólo puedo mantenerme cerca de la orilla con muy poca vela.`"
Pero para el remanente que tenía los ojos abiertos,
era evidente que su hombre interior crecía cada vez más vivo y fuerte,
llegando a ser como un árbol verde y fructífero en la vejez.
Las últimas dos o tres décadas de su vida,
fueron tiempos de especiales aflicciones internas y externas,
que se levantaban de diversas fuentes.
A finales del siglo 18,
la mayor parte de los que quedaban de la Sociedad de Amigos en Irlanda,
se habían apartado de la Verdad, y lamentablemente,
habían abrazado los principios del deísmo^
footnote:[El _deísmo_ es la posición filosófica y teológica
que rechaza la revelación como fuente de conocimiento divino,
y afirma que la razón humana y la observación del mundo natural son los únicos
medios lógicos y fiables para determinar la existencia y la voluntad del Creador.]
y el amor a este mundo.
Las reuniones en Dublín se hicieron cada vez más
dolorosas para los miembros vivos de la Sociedad,
y la verdadera comunión era escasa.
Además, fue profundamente probado, primero por la repentina muerte de su única hija,
seguida por la pérdida de su valiosa y muy amada esposa.
Pero a pesar de todo,
los pies de John Conran permanecieron firmes sobre la Roca inamovible,
y terminó fielmente su carrera con acción de gracias y rendición.__
